screepsplus:
  url: 'https://screepspl.us/api/stats/submit'
  token: <SCREEPSPLUS_TOKEN>

servers:
  screeps:
    token: <SCREEPS_TOKEN>
    shards:
    - shard1
    segments: [99]
    memory:
    - stats
    console:
      prefix: 'STATS'
      seperator: ';'
  screepsplus:
    host: server1.screepspl.us
    port: 443
    secure: true
    username: ags131
    password: <PASS>
    segments: [99]
    memory:
    - stats
    console:
      prefix: 'STATS'
      seperator: ';'
  